<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
    <TerrariaInstallPath Condition="'$(TerrariaInstallPath)' == ''">$(MSBuildThisFileDirectory)..\..\work\terraria-runtime\game</TerrariaInstallPath>
    <XnaAssemblyRoot Condition="'$(XnaAssemblyRoot)' == ''">C:\Windows\Microsoft.NET\assembly\GAC_32</XnaAssemblyRoot>
  </PropertyGroup>
</Project>
